### PR TITLE
Added logo position option and formatting

### PR DESCRIPTION
**Pull request by AlexanderWright**
Added PITCHME.yaml option: logo-position
This takes the following settings: 

- top-left
- top-right
- bottom-left
- bottom-right

The default is top-left, maintaining existing behaviour.

### CODE REVIEW

**Comment by gitpitch** [comment]
Hi @AlexanderWright thanks very much for submitting this PR. I've just been reviewing it and the implementation all looks good. But I'm not 100% sold on the utility of allowing logos in the bottom-left and bottom-right positions as they can (and do) clash with footers and the navigation-controls respectively.

Perhaps a bottom-left logo could automatically disable/hide any footer. But navigation-controls are fixed in the bottom-right (per reveal.js). 
 
That said, I'm very open to consider uses cases that I simply have not thought of yet. What use-case prompted you to request this feature and to support the bottom-left/right positions in your PR?

**Comment by AlexanderWright** [comment]
Hi,
Our organisation has recently created new branding, and one of the positions of choice (by the design company) is the bottom right. I added bottom left mostly for completeness, as I considered it up to the user to work out if that worked for their presentation.

The other position I can use is top right, so I'd be perfectly happy removing the two bottom positions, but perhaps others might make use of them?

I'll resubmit the PR with just the top for now.

**Comment by gitpitch** [comment]
@AlexanderWright thanks for this feedback, very helpful for me certainly and much appreciated. I've been thinking this over and I can see various use cases where having the logo even in the bottom-right position could make sense (if the presentation is configured for [auto-play](https://github.com/gitpitch/gitpitch/wiki/Auto-Slide-Setting) for example).

So I'm going to re-open your original PR and merge it. Thanks again for contributing to GitPitch.

**Comment by AlexanderWright** [comment]
You are very welcome!

This was my first ever Pull Request, so I have a 100% acceptance rate! Should I stop there? ;-)

**Pull request merged**
